version: '3'

services:
  app:
    build: .

    # Esse command vai sobrescrever o da imagem
    command: ./.docker/start.sh
    ports:
      - 4000:4000
    volumes:
      - .:/home/node/app
  postgres:
    container_name: con-db-codiflix-catalog-local
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: codeflix-catalog-db
    volumes:
      - postgres:/data/postgres
    ports:
      - '5433:5432'

volumes:
  postgres:
    driver: local
