version: '3'

services:
  app:
    build: .

    # Esse command vai sobrescrever o da imagem
    command: ./.docker/start.sh
    ports:
      - 4000:4000
    volumes:
      - .:/home/node/app
  postgres:
    image: postgres:16.0
    restart: always
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: